name: the_red_apple
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  overlay_support: ^2.1.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  intl: ^0.20.2
  image_picker: ^1.0.4
  http: ^1.3.0
  firebase_messaging: ^16.0.0
  firebase_storage: ^13.0.0
  firebase_database: ^12.0.0
  flutter_image_compress: ^2.3.0
  url_launcher: ^6.2.5
  table_calendar: ^3.2.0
  animated_notch_bottom_bar:
  video_player: ^2.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
# ✅ App Launcher Icon config (यह हमेशा बाहर होना चाहिए)
flutter_icons:
  android: true
  ios: true
  image_path: "Assets/images/apple_logo_2.jpg"

flutter:
  uses-material-design: true

  assets:
    - Assets/images/

