// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsrwgH6aUJ1BB7XFfoQEXgXH3-3Y2-1tM',
    appId: '1:839007999760:android:779778b1bbadb9ced33795',
    messagingSenderId: '839007999760',
    projectId: 'the-red-apple-28f19',
    databaseURL: 'https://the-red-apple-28f19-default-rtdb.firebaseio.com',
    storageBucket: 'the-red-apple-28f19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC2giUZNsz0MtY9T1LE01IRWsUwYKUJxo',
    appId: '1:839007999760:ios:d0216bd1e56ba0b6d33795',
    messagingSenderId: '839007999760',
    projectId: 'the-red-apple-28f19',
    databaseURL: 'https://the-red-apple-28f19-default-rtdb.firebaseio.com',
    storageBucket: 'the-red-apple-28f19.firebasestorage.app',
    androidClientId: '839007999760-kora1ut1fi2okho6loh6sp67873bee5m.apps.googleusercontent.com',
    iosClientId: '839007999760-jsc9i064ts2teqquueqdt9ffrqkr98a2.apps.googleusercontent.com',
    iosBundleId: 'com.theredapple.theRedApple',
  );
}
